### Register user/admin
POST {{url}}auth/register
Content-Type: application/json

{
  "username": "admin",
  "password": "admin",
  "role": "admin"
}

> {% client.global.set("token", response.body.token); %}

### Register user/user
POST {{url}}auth/register
Content-Type: application/json

{
  "username": "user",
  "password": "user",
  "role": "user"
}

> {% client.global.set("token", response.body.token); %}

### Login as admin
POST {{url}}auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

> {% client.global.set("token", response.body.token); %}

### Login as user
POST {{url}}auth/login
Content-Type: application/json

{
  "username": "user",
  "password": "user"
}

> {% client.global.set("token", response.body.token); %}

###
GET {{url}}auth/user
Authorization: Bearer {{token}}

###
GET {{url}}auth/admin
Authorization: Bearer {{token}}
